### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by larsekman** [SocialbitGmbH/SwiftAddressBook#1]
If I include this file, I get "Command failed due to signal: Segmentation fault: 11" if I try to compile my project. The compilation error does not reference SwiftAddressBook.swift, but a completely unrelated class. If I comment out the offending code (which compiles fine without SwiftAddressBook.swift in the project), another unrelated class gets the same error.

I don't even reference the code anywhere. And if I remove the file from the project, the project compiles fine.

Any idea what's going on?

**Comment by TAKeanice** [comment]
Good morning!

Segmentation fault usually refers to some write into a memory region which is not accessible to your program at runtime. That´s often related to bugs in the pointer arithmetics when using C (like array[-1] or whatever). Since you are getting this at compile time, it must be the compiler having a bug. I also had this problem in relation to Swift, but it solved itself (not sure any more what I have done for that, but for sure I have not done anything special)
If you have resolved the issue or if you have any other feedback on SwiftAddressBook, I´d love to know!

Yours,
Tassilo Karge

**Comment by TAKeanice** [comment]
@larsekman SwiftAddressBook is much more stable now and inside a pod. I hope that issue is gone for you now!
