### ISSUE TITLE
sourceName is not correct??

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#26]
Hi!
For some reason I do not get the correct sourceName for the added accounts:

I've added the Accounts named "iCloud", "MANDELKIND" and "Private" to my device.
Obviously the iCloud is the regular iCloud account - "MANDELKIND" and "Private" are simply CardDav accounts.

When I now try to access the sourceName i receive the following:

    iCloud -> 'Card'
    MANDELKIND -> 'Pause'
    Private -> 'Global Addressbook'

Why I do not just receive the name entered on the device...?!

**Comment by TAKeanice** [comment]
To answer shortly, I cannot check that right now, but since all that the getter of sourceName does is running `ABRecordCopyValue(internalRecord, kABSourceNameProperty)?.takeRetainedValue() as? NSString` there is no conversion here, and I guess it´s just ABAddressBook brainfuck. But I´ll look into it.

**Comment by TAKeanice** [comment]
http://stackoverflow.com/questions/5609690/addressbook-how-to-get-names-of-different-exchange-sources
Since Addressbook has not changed a lot so far, i guess this is the correct answer. Sorry :)

**Comment by TAKeanice** [comment]
What you can do is save names for those sources within your app - the ids of the sources stay the same, so you can use them as keys
