### ISSUE TITLE
Cannot ask permission if user revoke privileges

### ISSUE THREAD

**Issue by PGLongo** [SocialbitGmbH/SwiftAddressBook#49]
The first time you use:

```swift
swiftAddressBook?.requestAccessWithCompletion({ (success, error) -> Void in
```

it works correctly, but if the user revoke the permission and you try to check it again swiftAddressBook is always nil

**Comment by TAKeanice** [comment]
I think that is the correct behavior. Since the request alert is blocking, an app could force the user to allow access otherwise by requesting over and over again as soon as the user has denied access. Try requesting the next day, perhaps there is a limit of one request per day. You can still check permissions and ask the user to enable them from settings if you wish.

**Comment by PGLongo** [comment]
Ok. I think you're right.

Thanks

**Comment by TAKeanice** [comment]
If you notice anything that you think is wrong, feel free to ask again!
