### ISSUE TITLE
Need a public initializer on SwiftAddressBook

### ISSUE THREAD

**Issue by arctouch-ericchamberlain** [SocialbitGmbH/SwiftAddressBook#59]
Hello,

We need a public initializer, so we can have additional instances of SwiftAddressBook running off of the main thread.

Unfortunately, I'm not in a position to agree to the licensing terms for pull request submissions, could someone add a public initializer to the SwiftAddressBook class?

**Comment by TAKeanice** [comment]
There should never be more than one instance of the AddressBook, as it is not thread safe. Can you explain me what you're planning on, then maybe we can find a better solution.

**Comment by TAKeanice** [comment]
My description is bad. What I mean is, that you can't use multiple instances at the same time anyway. Additionally, creating multiple instances leads to issues because you would have to reset all instances as soon as you modify one, in order to keep them synchronized.

**Comment by arctouch-ericchamberlain** [comment]
One instance, or multiple instances, either way, synchronization is an issue when the address book is modified external to the running app.

The use case is a long running synchronization task that reads from the address book.  The task takes too long to run on the main thread and would block the UI.  The task is read only, as are the address book tasks that run on the main thread.  Synchronization between the two instances is not an issue for this use case.

**Comment by TAKeanice** [comment]
There is no dispatch done in SwiftAddressBook. Maybe I am wrong, but you should be able to call any function in SwiftAddressBook from a dispatch block, which would cause it to run off the main thread.

**Comment by arctouch-ericchamberlain** [comment]
Wouldn't that cause one ABAddressBook instance to get called from multiple threads?

**Comment by TAKeanice** [comment]
Ok, I will look up the threading issue with ABAddressBook again. I thought you must never even access different instances concurrently. But maybe I am erring here. I would, if necessary, change the initializer. But otherwise, just always dispatch to the background queue, and wait with the main thread if you want to use the results directly.

**Comment by TAKeanice** [comment]
Ok, seems like you were completely right. According to the documentation, one can solve the threading issues by creating a new AddressBook reference. I will add a public initializer with a big warning, because that introduces issues like "you must not pass around references between threads", "keep your instance in your thread", "reset when you want the changes in the other instances as well" and so on...

**Comment by purrrminator** [comment]
My problem is relevant to this issue. Imagine the case:
1. app requests permission to access address book
2. user denies the permission
3. user changes his mind and grants permissions through Settings - Privacy
4. app has not chance to reinit the `public let swiftAddressBook` which became nil since user denied in very first permission request.

**Comment by TAKeanice** [comment]
Good point, @purrrminator ! I will address that in another commit. Now I have first given you a class function to instantiate additional instances.

**Comment by TAKeanice** [comment]
Another link for information about using AddressBook multithreaded: http://stackoverflow.com/questions/2382388/iphone-multi-threaded-addressbook-manipulation

**Comment by purrrminator** [comment]
@TAKeanice some updates on my problem. I seems like when I'm testing on a real device (the problem I described was detected on a simulator) the app re-lauch every time I change the privacy settings. So maybe there is no need for public init for me, as the singleton reinitialized after app relaunch.

**Comment by TAKeanice** [comment]
I have just tested the same thing :smile: In this case just make your app restart to the same location where it was killed, and you will have a seamless experience. Still, the public initializer is useful for multithreaded solutions.
