### ISSUE TITLE
Is this extension compatible with Swift 2?

### ISSUE THREAD

**Issue by bobanda87** [SocialbitGmbH/SwiftAddressBook#63]

**Comment by TAKeanice** [comment]
There is a Swift2 branch. The changes there were not programmed by me and I did not have the time to test them. Please check out this branch, try it and report here if you find any issues! As long as ABAddressBook is not removed from iOS (it is deprecated in 9.0, though), I am planning to keep this wrapper up to date :smiley:

**Comment by TAKeanice** [comment]
On the iOS9 simulator, the tests fail. I think they have actually removed the old AddressBook framework from the operating system, since they are now offering a [new address book framework](https://developer.apple.com/library/prerelease/ios/documentation/Contacts/Reference/Contacts_Framework/index.html#//apple_ref/doc/uid/TP40015328). Although, I have not found any place where they state directly, that the deprecation means the removal of the framework at the same time. Functions and methods are often left in place for quite a while after deprecation.

I was not able to verify with the older simulators yet, because I am running into errors running or trying to reinstall the iOS8 Simulators. Most probably I first have to turn of rootless to allow that feature, in that case it would be quite poor by apple (why does that simulator need to modify system files?)

**Comment by dkharrat** [comment]
@TAKeanice I just tested on iOS 9 and got it to work. In addition to using the swift_2 branch, I also had to apply the change described here: https://github.com/SocialbitGmbH/SwiftAddressBook/pull/64 in SwiftAddressBookHelperMethods.swift

Specifically, it seems like in Swift 2, you can't cast `CFArray?` into `[ABRecord]`. You have to cast it to `NSArray` first:

    let swiftRecords = (records as? [ABRecord])?.map {(record : ABRecord) -> SwiftAddressBookPerson in

changes to:

    let swiftRecords = (records as NSArray? as? [ABRecord])?.map {(record : ABRecord) -> SwiftAddressBookPerson in

**Comment by TAKeanice** [comment]
That helped! Another thing that I had to change was 17c454f (optional unwrapping or better this together with casting conditionally afterwards somehow failed).

**Comment by TAKeanice** [comment]
Tests are now running, with iOS9 (the interface was not removed). Travis CI is just checking, and afterwards I will merge the swift_2.0 branch into master. Thanks for your help!
