### ISSUE TITLE
Crash when `ABPersonCopyImageData` returns nil

### ISSUE THREAD

**Issue by amitai-hoze** [SocialbitGmbH/SwiftAddressBook#83]
Hi, we're using your great library, version 0.6.1, and getting a crash from our crash reporting system (Crashlytics) on [SwiftAddressBookPerson.swift line 65](https://github.com/SocialbitGmbH/SwiftAddressBook/blob/ba596395554bbf6bfce64ee642f31234e55ce8cc/Pod/Classes/SwiftAddressBookPerson.swift#L65).

We're getting an `EXC_BREAKPOINT` which is most probably a swift fatal error, specifically in this case, unwrapping a `nil`. We got 9 crashes from 7 users after only 3 days in production.. We mainly suspect that `ABPersonCopyImageData(internalRecord)` returns a `nil`, but couldn't reproduce. Maybe the `ABPersonHasImageData` doesn't guarantee that you won't get a `nil`, and extra protection is needed..

Here is the crash report image from Crashlytics:
![crash](https://cloud.githubusercontent.com/assets/7767185/13904969/caf55b44-eeba-11e5-8d4c-86143251c2eb.png)

**Comment by TAKeanice** [comment]
Even then the optional unwrapping should take care of the issue. Please make sure you are accessing the address book in a thread safe manner (one instance of SwiftAddressBook may only be used by one thread simultaneously). Dispatch queues were a constant source of random errors during testing in all iterations so far, because the app was executed in parallel to the tests, but the same instance of SwiftAddressBook was used.

Happy to know that this library qualified for your production app! Let me know if you need any other help.

**Comment by TAKeanice** [comment]
There is a new version now. Please check out the newest version and close if it fixes your issue. I am not sure whether re-checking the image data after ABPersonHasImageData returned false has any effect, but let us hope the best.

**Comment by TAKeanice** [comment]
By the way: Optional unwrapping should have prevented the issue, but it wasn't optional in the previous version! I already had this issue, but unfortunately my tests didn't catch that regression bug, when I published 0.6.1. I would be glad if you could add a test reproducing a state where ABPersonHasImageData returns true, but copying returns nil, so that future versions can reliably avoid such problems.

**Comment by amitai-hoze** [comment]
Hi, thanks a lot for your quick response! :+1: 

We weren't able to reproduce it, just received crash reports regarding the matter..
We'll update to the newest release, and let you know if this bug happens again.

**Comment by TAKeanice** [comment]
You could catch the error while still producing a report, that would at least prevent a bad customer satisfaction. Also interesting would be if the bug happens on all kinds of devices, with all or just some contacts, everytime on the same contact or just the first time or randomly on accessing the image.

**Comment by TAKeanice** [comment]
Anything new on this one?

**Comment by TAKeanice** [comment]
Going to close because there was no news any more.

**Comment by amitai-hoze** [comment]
Hi, sorry for the late reply, since we updated the version the error didn't happen again, thanks a lot!

**Comment by TAKeanice** [comment]
Never mind :) I am happy that the fix could help you!
