### ISSUE TITLE
registerExternalChangeCallback is missing

### ISSUE THREAD

**Issue by Sega-Zero** [SocialbitGmbH/SwiftAddressBook#98]
According to the [source code](https://github.com/SocialbitGmbH/SwiftAddressBook/blob/917a770931b7994cbe523d6a071369d5ce02d50c/Pod/Classes/SwiftAddressBookWrapper.swift#L89), the function is commented out, what's the reason of it?

**Comment by TAKeanice** [comment]
You are right, the commit message and a source code comment should mention a reason. I can´t remember whether I did that or one of the other contributors in that project, but it seems plausible that the reason was to resolve a bug in swift3. The support for this function was limited in the first place due to the necessity of c pointer arithmetic, which just didn´t work in pure swift. Later, a contributor added the functionality by creating the two objective-c classes contained in this project. The conversion to swift3 was difficult and I had already given up on it, while others still tried and managed with the version you are seeing now. I would be happy if you tried the functionality of the function, test with travis ci and create a pull request if everything works!

**Comment by TAKeanice** [comment]
if you don´t depend on supporting iOS 8 or older, I recommend you to use the newer addressBook api provided by apple. They finally revised this the last tedious front-facing c api in iOS9

**Comment by Sega-Zero** [comment]
I, actually, had to use `SwiftAddressBookObserver.startObserveChanges` to achieve get that callback working again. And it's 100% working on iOS 8on my swift 3 project.

**Comment by TAKeanice** [comment]
The tricky OS is iOS9 though. The api and its headers got out of sync in these version for a while.

**Comment by Sega-Zero** [comment]
I use SwiftAddressBook for iOS 8 only. I do believe there's no good reason to ignore Contacts.framework on iOS 9+

**Comment by TAKeanice** [comment]
There is no reason to ignore it, but if you want to use the same source code in all iOS versions, SwiftAddressBook still comes in handy. I agree that one should only use the new Contacts api in iOS 9-and-upwards-only apps

**Comment by TAKeanice** [comment]
I commented in the lines, travis says it´s ok, master is now updated, pod is version 0.7.1
